name: Badge


on:
  workflow_call:
    # inputs:
    #     name:
    #         required: true
    #         type: string
    # secrets:
    #     GITHUB_TOKEN:
  

jobs:
    badge:
      runs-on: ubuntu-latest
      steps:
        - id: status
          run: echo "##[set-output name=data;]$(date)"
        - name: Pass-Fail badge
          uses: RubbaBoy/BYOB@v1.3.0
        #   env:
        #     GITHUB_TOKEN: ${{ github.token }}
          with:
            NAME: "name"
            LABEL: 'label'
            STATUS: ${{ steps.date.outputs.data }}
            COLOR: green
            GITHUB_TOKEN: $GITHUB_TOKEN



            # echo "dir=$CCACHE_DIR" >> $GITHUB_OUTPUT
